/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_BLE_ADV_PACKET_ADV_PACKET_PB_H_INCLUDED
#define PB_BLE_ADV_PACKET_ADV_PACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BLE_adv_packet {
    int32_t rssi;
    int32_t dataLen;
} BLE_adv_packet;


/* Initializer values for message structs */
#define BLE_adv_packet_init_default              {0, 0}
#define BLE_adv_packet_init_zero                 {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BLE_adv_packet_rssi_tag                  2
#define BLE_adv_packet_dataLen_tag               3

/* Struct field encoding specification for nanopb */
#define BLE_adv_packet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              2) \
X(a, STATIC,   SINGULAR, INT32,    dataLen,           3)
#define BLE_adv_packet_CALLBACK NULL
#define BLE_adv_packet_DEFAULT NULL

extern const pb_msgdesc_t BLE_adv_packet_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BLE_adv_packet_fields &BLE_adv_packet_msg

/* Maximum encoded size of messages (where known) */
#define BLE_adv_packet_size                      22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
